name: navo-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.24
  - astropy>=5.2
  - matplotlib>=3.2
  - jupyterlab>=3.1
  - pyvo>=1.4
  - scipy>=1.0
  - pip
  - pip:
    - jupytext>=1.14
    - astroquery
    - --pre
