name: navo-env
channels:
  - astropy
dependencies:
  - python=3.9
  - numpy
  - astropy>=4.1
  - matplotlib
  - jupyterlab>=3.0
  - pip
  - pip:
    - astroquery
    - jupyter-offlinenotebook
    - git+https://github.com/astropy/pyvo.git@c2bf90c16bcfd9c4
    - aplpy
