name: navo-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - astropy>=6.0
  - matplotlib>=3.8
  - jupyterlab>=4.0
  - pyvo>=1.4.2
  - scipy>=1.11
  - pip
  - pip:
    - jupytext>=1.14
    - astroquery
    - --pre
