name: navo-env
channels:
  - astropy
dependencies:
  - python=3.8
  - numpy
  - astropy>=4.1
  - matplotlib>=3.1
  - jupyterlab>=3.0
  - aplpy
  - pip
  - pip:
    - astroquery
    - jupyter-offlinenotebook
    - git+https://github.com/astropy/pyvo.git@c2bf90c16bcfd9c4
