name: navo-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - astropy>=4.1
  - matplotlib
  - requests
  - jupyterlab>=2.0
  - scipy
  - aplpy
  - pip
  - pip:
    - astroquery
    - jupyter-offlinenotebook
    - pyvo>=1.1
