name: navo-env
channels:
  - astropy
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.18
  - astropy>=5.0
  - astroquery>=0.4.4
  - matplotlib>=3.1
  - jupyterlab>=3.1
  - pyvo>=1.4
  - scipy
