version: 2.1

jobs:

  build-docs:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r .binder/requirements.txt -r doc-requirements.txt

      - run:
          name: Build html
          no_output_timeout: 30m
          command: |
            # Run only the notebooks that don't have outputs included, more thorough testing should be done in other jobs
            sphinx-build -b html -D nb_execution_mode=auto . _build/html

      - store_artifacts:
          path: _build/html

workflows:
  version: 2
  default:
    jobs:
      - build-docs
